name: deploy to gh pages
run-name: ${{github.actor}} is running deployment
on: 
  push: 
    branches:
      - main
jobs: 
  deploy-to-gh-page:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: 18
      - uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: ${{secrets.CREDENTIALS}}
      - name: install all dependecies
        run: yarn
      - name: build the dist
        run: git config --global user.email ${{vars.EMAIL}} && git config --global user.name ${{vars.NAME}} && yarn build 
      - name: after building the dist file 
        run: yarn deploy