name: deploy to gh pages
run-name: ${{github.actor}} is running deployment
on: 
  push: 
    branches:
      - main
jobs: 
  deploy-to-gh-page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: 18
      - name: install all dependecies
        run: yarn
      - name: build the dist
        run: yarn build 
      - name: after building the dist file 
        run: yarn deploy